In [1]:
import numpy as np
import pandas as pd

#### Nominal Data

##### 1.Using Pandas

In [2]:
df = pd.DataFrame({'color':['orange','black','yellow','blue']})
df

    color
0  orange
1   black
2  yellow
3    blue

In [3]:
df2 = pd.get_dummies(df,dtype ='int')
df2

   color_black  color_blue  color_orange  color_yellow
0            0           0             1             0
1            1           0             0             0
2            0           0             0             1
3            0           1             0             0

##### 2. Using one hot encoding/SK Learn

In [4]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output = False)

In [5]:
ohe.fit_transform(df[['color']])

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [6]:
# convert above array -> dataframe -> concatenate to dataframe -> remove original column

#### Ordinal Data

##### ordinal encoding

In [7]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['Low','Medium','High']])

In [8]:
data = np.array([['Low'],['Medium'],['High']])
oe.fit_transform(data)

array([[0.],
       [1.],
       [2.]])

##### Label Encoding e.x 1

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(df['color'])

array([2, 0, 3, 1])

##### Label Encoding e.x 2

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
data = ['S','M','L','XL']

# Initialize encoder
le = LabelEncoder()

#Transform 
encoded = le.fit_transform(data)
encoded

array([2, 1, 0, 3])