In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("C:/Users/ASUS/Desktop/FBS/Data science/Dataset/home_prices.csv")
data.head()

   area_sqr_ft  bedrooms color  price_lakhs
0         3774         2   Red          216
1         1460         3  Gray           88
2         1894         4  Gray          147
3         1730         2  Blue           84
4         1695         1  Blue           77

In [3]:
data.describe()

       area_sqr_ft    bedrooms  price_lakhs
count   300.000000  300.000000   300.000000
mean   2371.990000    3.013333   148.050000
std     942.766953    1.446882    52.873113
min     601.000000    1.000000    15.000000
25%    1620.750000    2.000000   107.750000
50%    2342.500000    3.000000   151.000000
75%    3206.000000    4.000000   191.000000
max    3997.000000    5.000000   250.000000

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   area_sqr_ft  300 non-null    int64
 1   bedrooms     300 non-null    int64
 2   color        300 non-null    object
 3   price_lakhs  300 non-null    int64
dtypes: int64(3), object(1)
memory usage: 9.5+ KB

In [5]:
data['color'].unique()

array(['Red', 'Gray', 'Blue', 'Yellow', 'Green', 'White'], dtype=object)

In [6]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output = False)

In [7]:
encoded_array = ohe.fit_transform(data[['color']])

In [8]:
encoded_data = pd.DataFrame(encoded_array,columns = ohe.get_feature_names_out(['color']))

In [9]:
data = pd.concat([data, encoded_data], axis=1)

In [10]:
data.drop('color', axis=1, inplace=True)

In [11]:
data.head()

,area_sqr_ft,bedrooms,price_lakhs,color_Blue,color_Gray,color_Green,color_Red,color_White,color_Yellow
0,3774,2,216,0.0,0.0,0.0,1.0,0.0,0.0
1,1460,3,88,0.0,1.0,0.0,0.0,0.0,0.0
2,1894,4,147,0.0,1.0,0.0,0.0,0.0,0.0
3,1730,2,84,1.0,0.0,0.0,0.0,0.0,0.0
4,1695,1,77,1.0,0.0,0.0,0.0,0.0,0.0